fix mdr

diff --git a/mdr b/mdr
--- a/mdr
+++ b/mdr
@@ -4,6 +4,7 @@
 # MDR xml tool cli
 # Author: muink
 # Github: https://github.com/muink/MDR_Proxy
+# License: MIT License
 #
 
 # Init
@@ -44,14 +45,26 @@ Options:\n\
 \n"
 }
 
+# downloadRaw [var_Raw]
 downloadRaw() {
   local downUrl='https://info.update.sony.net/${categoryID}/${serviceID}/info/info.xml'
 
-  curl —XGET -Lso - \
+  curl -XGET -LsfSo - \
     -H "User-Agent: Dalvik/2.1.0 (Linux; U; Android 11; XQ-AT52 Build/58.1.A.5.159)" \
     -H "Accept-Encoding: gzip" \
-    $(eval "echo \"$downUrl\"") |
-  gzip -d 2>/dev/null | base64
+    $(eval "echo \"$downUrl\"") \
+  2> >(
+    local err="$(tee)"
+    local errcode="$(echo "$err"|sed -En "s/^curl: \(([0-9]+)\).*/\1/p")"
+    [ -n "$err" ]&& >&2 echo -e "$(basename $0): downloadRaw: $err" && exit ${errcode:-0}
+  ) \
+  >  >(
+    if [ -n "$1" ];then
+      eval "$1=\"\$(tee|gzip -d 2>/dev/null|base64)\""
+    else
+      tee|gzip -d 2>&-
+    fi
+  )
 }
 
 # splitRaw <val_Raw> <var_head> <var_cryptedData>
@@ -86,7 +99,7 @@ case "$daid" in
     ???0003)has=sha1;;
   *)has=;;
 esac
-if [ -z "$enc" -o -z "$has" ]; then >&2 echo -e "$(basename $0): Undefined encryption method:\n\t$eaid:{eaid:-null}\n\tdaid:${daid:-null}" && exit 1; fi
+if [ -z "$enc" -o -z "$has" ]; then >&2 echo -e "$(basename $0): Undefined encryption method:\n\t$eaid:{eaid:-null}\n\tdaid:${daid:-null}"; exit 1; fi
 # Decrypt
 case "$enc" in
   none)eval "$3=\$(echo \"\$2\"|base64 -d|base64)";;
@@ -103,14 +116,14 @@ case "$has" in
   md5)eval "datahash=\$(echo \"\$$3\"|base64 -d|md5sum -b|cut -f1 -d' ')"; hash="$(echo -n "$datahash$serviceID$categoryID"|md5sum -b|cut -f1 -d' ')";;
   sha1)eval "datahash=\$(echo \"\$$3\"|base64 -d|sha1sum -b|cut -f1 -d' ')"; hash="$(echo -n "$datahash$serviceID$categoryID"|sha1sum -b|cut -f1 -d' ')";;
 esac
-if [ "$hash" != "$digest" ]; then >&2 echo -e "$(basename $0): Data checksum error. Decryption failed." && exit 1; fi
+if [ "$hash" != "$digest" ]; then >&2 echo -e "$(basename $0): Data checksum error. Decryption failed."; exit 1; fi
 }
 
 
 
 # Main
 # Get options
-[ "$1" == "--" ]&& _help && exit
+[ "$1" == "--" ]&& _help && exit 1
 while [ -n "$1" ]; do
   case "$1" in
     --help)
@@ -148,9 +161,9 @@ done
 #
 
 # Output
-rawData=$(downloadRaw)
-[ -z "$rawData" ]&& >&2 echo -e "$(basename $0): Raw info.xml download failed.\n\tPlease use the correct categoryID/serviceID\n\t and check the network connection." && exit 1
+downloadRaw rawData; errCode="$?"
+[ -z "$rawData" ]&& >&2 echo -e "$(basename $0): Raw info.xml download failed.\n\tPlease use the correct categoryID/serviceID\n\t and check the network connection." && exit ${errCode:-0}
 splitRaw "$rawData" header cryptedData
 decryptData "$header" "$cryptedData" decryptedData
-echo "$decryptedData"|base64 -d
+echo "$decryptedData"
 
