GM

diff --git a/mdr b/mdr
--- a/mdr
+++ b/mdr
@@ -98,19 +98,35 @@ if [ -z "$enc" -o -z "$has" ]; then >&2 echo -e "$(basename $0): Undefined encry
 case "$enc" in
   none)       eval "$3=\$(echo \"\$2\"|base64 -d|base64)";;
   des-ede3)   eval "$3=\$(echo \"\$2\"|base64 -d|openssl enc -d -des-ede3 -K 000000000000000000000000000000000000000000000000 -nopad|base64)";;
-  aes-128-ecb)eval "$3=\$(echo \"\$2\"|base64 -d|openssl enc -d -aes-128-ecb -K 4FA27999FFD08B1FE4D260D57B6D3C17 -nopad|base64)";;
+  aes-128-ecb)eval "$3=\$(AESdecipher \"\$2\")";;
 esac
 # openssl enc -e -des-ede3 -in des-ede3_decrypted.xml -out des-ede3_out.txt -K 000000000000000000000000000000000000000000000000 -nosalt -nopad
 # openssl enc -d -des-ede3 -in des-ede3_crypted.xml -out des-ede3_in.txt -K 000000000000000000000000000000000000000000000000 -nopad
 # openssl enc -e -aes-128-ecb -in aes-128-ecb_decrypted.xml -out aes-128-ecb_out.txt -K 4FA27999FFD08B1FE4D260D57B6D3C17 -nosalt -nopad
 # openssl enc -d -aes-128-ecb -in aes-128-ecb_crypted.xml -out aes-128-ecb_in.txt -K 4FA27999FFD08B1FE4D260D57B6D3C17 -nopad
 # Verify
-case "$has" in
-  none)hash="$digest";;
-  md5) datahash=$(echo "${!3}"|base64 -d|md5sum -b |cut -f1 -d' '); hash="$(echo -n "$datahash$serviceID$categoryID"|md5sum -b |cut -f1 -d' ')";;
-  sha1)datahash=$(echo "${!3}"|base64 -d|sha1sum -b|cut -f1 -d' '); hash="$(echo -n "$datahash$serviceID$categoryID"|sha1sum -b|cut -f1 -d' ')";;
-esac
-if [ "$hash" != "$digest" ]; then >&2 echo -e "$(basename $0): Data checksum error. Decryption failed."; exit 1; fi
+for i in {0..1}; do
+  case "$has" in
+    none)hash="$digest";;
+    md5) datahash=$(echo "${!3}"|base64 -d|md5sum -b |cut -f1 -d' '); hash="$(echo -n "$datahash$serviceID$categoryID"|md5sum -b |cut -f1 -d' ')";;
+    sha1)datahash=$(echo "${!3}"|base64 -d|sha1sum -b|cut -f1 -d' '); hash="$(echo -n "$datahash$serviceID$categoryID"|sha1sum -b|cut -f1 -d' ')";;
+  esac
+  if [ "$hash" != "$digest" ]; then
+    eval "$3=\$(AESdecipher \"\$2\" 1)"
+    [ "$i" -eq 0 ] && continue
+    >&2 echo -e "$(basename $0): Data checksum error. Decryption failed."; exit 1;
+  fi
+done
+}
+
+# AESdecipher <val_cryptedData> <bool_GM>
+#                               <'1'|''>
+AESdecipher() {
+  if [ -n "$2" ]; then
+    echo "$1"|base64 -d|openssl enc -d -aes-128-ecb -K 73E84A54D05837A8ACDC5D9E2D652B97 -nopad|base64
+  else
+    echo "$1"|base64 -d|openssl enc -d -aes-128-ecb -K 4FA27999FFD08B1FE4D260D57B6D3C17 -nopad|base64
+  fi
 }
 
 
