fix mdr

diff --git a/mdr b/mdr
--- a/mdr
+++ b/mdr
@@ -72,7 +72,7 @@ decryptData() {
   local headerSplit=(eaid daid digest)
   for _key in "${headerSplit[@]}"; do
     eval "local $_key=\$(echo \"\$1\"|sed -En \"/^\$_key:.*/I s|^\$_key:||i p\")"
-    if [ -z "$(eval "echo \$$_key")" ]; then >&2 echo -e "$(basename $0): Data header error."; return 1; fi
+    if [ -z "$(eval "echo \$$_key")" ]; then >&2 echo -e "$(basename $0): Data header error."; exit 1; fi
   done
 # Analytical header
 local enc has datahash hash
@@ -90,7 +90,7 @@ case "$daid" in
     ???0003)has=sha1;;
   *)has=;;
 esac
-if [ -z "$enc" -o -z "$has" ]; then >&2 echo -e "$(basename $0): Undefined encryption method:\n\t$eaid:{eaid:-null}\n\tdaid:${daid:-null}" && return 1; fi
+if [ -z "$enc" -o -z "$has" ]; then >&2 echo -e "$(basename $0): Undefined encryption method:\n\t$eaid:{eaid:-null}\n\tdaid:${daid:-null}" && exit 1; fi
 # Decrypt
 case "$enc" in
   none)eval "$3=\$(echo \"\$2\"|base64 -d|base64)";;
@@ -107,13 +107,14 @@ case "$has" in
   md5)eval "datahash=\$(echo \"\$$3\"|base64 -d|md5sum -b|cut -f1 -d' ')"; hash="$(echo -n "$datahash$serviceID$categoryID"|md5sum -b|cut -f1 -d' ')";;
   sha1)eval "datahash=\$(echo \"\$$3\"|base64 -d|sha1sum -b|cut -f1 -d' ')"; hash="$(echo -n "$datahash$serviceID$categoryID"|sha1sum -b|cut -f1 -d' ')";;
 esac
-if [ "$hash" != "$digest" ]; then >&2 echo -e "$(basename $0): Data checksum error. Decryption failed." && return 1; fi
+if [ "$hash" != "$digest" ]; then >&2 echo -e "$(basename $0): Data checksum error. Decryption failed." && exit 1; fi
 }
 
 
 
 # Main
 # Get options
+[ "$1" == "--" ]&& _help && exit
 while [ -n "$1" ]; do
   case "$1" in
     --help)
@@ -157,7 +158,7 @@ while [ -n "$1" ]; do
   shift
 done
 # Get parameters
-[ -z "$1" ]&& _help && exit
+#
 
 # Output
 rawData=$(downloadRaw)
@@ -171,5 +172,4 @@ if [ "$OUTT" == "true" ]; then
 else
   echo "$decryptedData"|base64 -d
 fi
-
 
